version: '3.8'

services:
  inventory:
    build: .
    ports:
      - '3000:3000'
    environment:
      - ENV_VAR_NAME=value
    volumes:
      - ./data:/opt/app/data
    restart: on-failure
